### ISSUE TITLE
Link back to repo from SPEC website

### ISSUE THREAD

**Issue by pllim** [scientific-python/specs#161]
From https://scientific-python.org/specs/ , it is not easier to come back to this GitHub repo. I propose to add a link so people can come to this repo more easily from that site.

**Comment by stefanv** [comment]
That sounds like a good idea; do you want to make a PR, or should I?

**Comment by pllim** [comment]
I do not know where the rendering code is. It is faster if you do it, but if you point me to the correct file, I won't mind filing a PR. Up to you. 😸

**Comment by stefanv** [comment]
It'd be great if you want to give it a shot!

The code lives [here](https://github.com/scientific-python/scientific-python.org/blob/main/layouts/specs/list.html) and [here](https://github.com/scientific-python/scientific-python.org/blob/main/layouts/partials/specs/spec_list.html).

**Comment by pllim** [comment]
Thanks for the pointers. What do you think about https://github.com/scientific-python/specs/pull/163 ?
