### ISSUE TITLE
SPEC Tools: tool to support calendar for SPEC0

### ISSUE THREAD

**Issue by bsipocz** [scientific-python/specs#173]
Ideally, the SPEC sets the logic of the versions, but the actual release and dates are not hard-wired in it but are provided by a separate tool.

**Comment by bsipocz** [comment]
version.py in the spec0 directory does parts of this. I think it should be moved outside of this policies repo into a tools repo, as well as the spec source docs to be cleaned up from all hard-wired version information, so this issues is probably shouldn't be closed just yet.

**Comment by munkm** [comment]
What if we create a `utils/` folder in this repo that holds all of our SPEC utility tools? Then other orgs/projects can use the tools associated with the specs, and their association with the SPECs are obvious?

**Comment by bsipocz** [comment]
OK, the remaining points to actually auto generate both the figure, and the drop text table using the script.

I suppose some JS wizardry would do the trick.

**Comment by bsipocz** [comment]
@alphapapa - this maybe something for you? We already have the python script that generates the dates, but didn't massaged it into a CI cron to auto generate the figure and the drop table in for the SPEC0 rendering. 
Ideally, it would be wonderful not to have those in the md file altogether, but pulled in from a generated file?

**Comment by alphapapa** [comment]
@bsipocz Hi, sure, I'd be glad to work on this, assuming that @jarrodmillman / @stefanv agree.  :)

**Comment by bsipocz** [comment]
Yeap, Jarrod was standing by my shoulders when I made the comment :)

**Comment by alphapapa** [comment]
@bsipocz Oh, apparently I can't assign issues on this repo.  Would you assign it to me please?

**Comment by bsipocz** [comment]
The process we converged on is good in practice, so I'm closing this issue.
