### ISSUE TITLE
SPEC4 clarification: nightly vs weekly

### ISSUE THREAD

**Issue by bsipocz** [scientific-python/specs#206]
See: https://github.com/scientific-python/specs/pull/203#issuecomment-1565066266

I believe the intention of the SPEC when it refers to `nightly` is really about a regularly distributed wheel of the developer version. Whether it is produced every day, or weekly or even fortnightly, still falls into the category and choosing between those could be left to the discretion of the libraries.

What do you all think? @rossbar @betatim

**Comment by betatim** [comment]
Yes, I think "nightly" should be read as "some semi regular interval, like daily, weekly or every three days". It is probably worth clarifying this in the SPEC.

Do you want to open a PR?
