### ISSUE TITLE
BUG: SPEC0 table should do numerical sort not alphabetical for versions

### ISSUE THREAD

**Issue by bsipocz** [scientific-python/specs#218]
Version 2022.10 should come after 2022.3 not before, the sorting of version numbers should not be alphabetical.

<img width="791" alt="Screenshot 2023-05-31 at 11 46 38" src="https://github.com/scientific-python/specs/assets/6788290/3806ea4a-d8ed-471c-bf80-b2ff4f1913b9">

I'm cc-ing @alphapapa as this is something to double-check when the figure and table get auto-generated for the front end.

**Comment by danieltomasz** [comment]
There is a problem with the part of Gant Chart with numpy, newer version are on the left, should be the other way

**Comment by stefanv** [comment]
This is the current output:

![image](https://github.com/scientific-python/specs/assets/45071/edf7ce6f-e69f-4966-a63b-49a8c6ec001f)

**Comment by stefanv** [comment]
(Once this PR gets merged.)
