### ISSUE TITLE
BUG: Spec0 has a rendering error

### ISSUE THREAD

**Issue by mattip** [scientific-python/specs#220]
The code rendering at the bottom of the document has an error `Syntax error in text mermaid version 10.1.0`

**Comment by stefanv** [comment]
Thanks, Matti, I think this is a duplicate of https://github.com/scientific-python/specs/issues/212

**Comment by stefanv** [comment]
I can confirm that this is a regression due to Hugo

**Comment by mattip** [comment]
Closing as a duplicate.
