### ISSUE TITLE
Explain "endorsement" term on SPEC index page

### ISSUE THREAD

**Issue by stefanv** [scientific-python/specs#228]
Also add a link to the more detailed explanation (Purpose & Process). Hover-tip over the term endorse.

**Comment by Carreau** [comment]
There is some reference to it here: https://scientific-python.org/specs/purpose-and-process/#decision-points

**Comment by bsipocz** [comment]
Maybe even a hover over one-liner.

**Comment by ivanov** [comment]
as discussed at the 2023-06-26 SPEC meeting

**Comment by jarrodmillman** [comment]
See https://github.com/scientific-python/scientific-python.org/pull/437
