### ISSUE TITLE
Handle SPEC 2

### ISSUE THREAD

**Issue by stefanv** [scientific-python/specs#229]
- [x] Remove attached website @jarrodmillman 
  - [x] #239 @jarrodmillman 
  - [x] Save meeting notes @jarrodmillman archived https://github.com/scientific-python/api-dispatch.scientific-python.org
  - [x] remove website from netlify @jarrodmillman 
- [ ] Update SPEC text @jarrodmillman #307

**Comment by rgommers** [comment]
That sounds like a great idea @MridulS. It'd be useful to have an overview of which projects are trying what, and some learnings. It's still early days in a way, but hopefully at some point one or a couple of patterns appear that can be adopted by others.
