### ISSUE TITLE
Involve sklearn in SPEC 7 discussion

### ISSUE THREAD

**Issue by stefanv** [scientific-python/specs#230]

**Comment by InessaPawson** [comment]
@stefanv This discussion happened in https://github.com/scientific-python/specs/pull/180 and during the 2024 Scientific Python Summit. Do you think we can close this issue now?

**Comment by bsipocz** [comment]
Would be nice to see at least one sklearn maintainer as coauthor on the SPEC (@thomasjpfan?), but I agree that this separate issue can be closed now as the SPEC discussion is on the radar.
