### ISSUE TITLE
SPEC 4: mention the retention policy in the SPEC

### ISSUE THREAD

**Issue by mattip** [scientific-python/specs#261]
It turns out there is a retention policy enforced by a github action that removes any artifact if
- there are already 5 previous version or
- the artifact is more than 30 days old

@bsipocz is that correct?

This should be part of the SPEC, and new projects should be notified of this policy.

xref scientific-python/upload-nightly-action#34

**Comment by jarrodmillman** [comment]
I thought #262 was supposed to close this. If not, we can reopen this.

**Comment by bsipocz** [comment]
Hah, I made the beginners mistake of not using the correct verb to auto-close. Sorry about that.
