### ISSUE TITLE
Revise wording to better convey the purpose of SPECs

### ISSUE THREAD

**Issue by cbrnr** [scientific-python/specs#280]
Following up the discussion in https://github.com/scientific-python/lazy_loader/pull/70, the way that SPECs are presented on the Scientific Python website can be misleading. It puts some (a lot of?) pressure on packages to adopt all SPECs, at least that's my impression. Since this is not intended, I think some modifications to the website might help clarify this. Here are some examples:

- The introductory sentence on the [main SPEC page](https://scientific-python.org/specs/) says: "SPECs provide operational guidelines for projects in the scientific Python ecosystem." If I develop a project in the scientific Python ecosystem, this sounds like I need to follow these guidelines. I guess the term "guidelines" is too strong, maybe "recommendations" or "suggestions"? I think it would be great if the first sentence already clarified that it's OK to not adopt any SPECs if it is not feasible, and that a project would still be part of the scientific Python ecosystem.
- The list of recommendations lists all SPECs as well as projects which have endorsed them. I think this is exactly the thing that's misleading projects into thinking that every good projects should strive to adopt as many SPECs as possible. After all, they get featured prominently on the website then. Honestly, I would remove all endorsing projects here, and maybe create a separate document, which describes projects that have adopted certain specs. This would give more room for presenting the pros and cons of each SPEC, and maybe make it clear that it's OK if a projects opts to not adopt a certain SPEC. It would also make it harder to see the amount of SPECs each project has adopted. Or maybe list projects which have supported a specific SPEC at the bottom of each SPEC page.
- On each SPEC page, and I'm now mainly talking about SPEC 1 (lazy loading), tone down the wording so that it is clear that no project has to adopt that SPEC. This also includes listing the pros and cons, which are already discussed, but maybe not prominently enough (only the advantages are listed near the top, the disadvantages get a short Caveats section much further into the text. For example, the introduction says: "This SPEC recommends a lazy loading mechanism—targeted at libraries—that avoids import slowdowns and provides explicit submodule exports." The libraries part is a bit unclear – when is a package a library? So after reading this, the message I get is that lazy loading is recommended. Period. I'd also include more caveats in this section (instead of footnotes), such as the rejection of the lazy import PEP, comments by some Python core devs why they are probably never going to include the mechanism, etc. This is extremely important information, which I had completely missed when we were discussing including lazy loading in MNE. At that time I just skimmed the SPECs page and thought "yeah, this sounds great, who doesn't want reduced import times for free?".

These are the things that I think could be easily improved. I can make a PR, but I think it makes more sense to discuss the changes here before that.

**Comment by jarrodmillman** [comment]
I am in general ok with this idea, but it is hard to say for sure without seeing a concrete PR to review. My main concerns are:

- The language should be terse, so people can read it.
- The language shouldn't become too legalistic.

It would also help it you (or anyone who sees this issue) could point at some concrete problems the SPECs are causing. For example, a PR discussion where someone is trying to pressure a project to adopt a SPEC or to follow a SPEC too exactly.

**Comment by jarrodmillman** [comment]
The idea behind the SPECs is that many projects face similar concerns and now each project has to decide on what guidelines they should adopt for their individual projects. For example, maybe a project wants to implement lazy imports. Without SPEC 1, each project could survey other projects to see if or how they implemented it. I've done that many times for projects I work on. It seems like it would be nice to have that information in one place. I also am not going to read a long convoluted document. So I want something short  and easy to follow.

We should say these are recommended guidelines. Not requirements. We've tried to do that, but it seems that people still view these as requirements or rules. 

A recommendation is "a suggestion or proposal as to the best course of action, especially one put forward by an authoritative body." A guidelines is "a general rule, principle, or piece of advice." I think that makes sense, but maybe we can water it down more if people are still viewing these as laws or requirements.

**Comment by cbrnr** [comment]
Let's not take this too far. I think what @keewis suggested is a good idea: include that paragraph on the main page, directly at the top. Otherwise, a recommendation is always something I should try to follow. Everybody likes to follow recommendations, right?

OTOH, this discussion revolves only around SPEC1 (lazy imports), so maybe this "recommendation" could be treated separately? E.g. a category "special-purpose SPECs for very specific use cases" (of course this shouldn't be the literal title)? All other SPECs can be recommended to any project in contrast to this one.

**Comment by jarrodmillman** [comment]
It applies to all the SPECs. I don't use SPEC 0 for all projects. For example, the lazy_loader package doesn't follow SPEC 0. It still supports Python 3.7.

**Comment by jarrodmillman** [comment]
> OTOH, this discussion revolves only around SPEC1 (lazy imports), so maybe this "recommendation" could be treated separately? E.g. a category "special-purpose SPECs for very specific use cases" (of course this shouldn't be the literal title)? All other SPECs can be recommended to any project in contrast to this one.

It applies to all the SPECs. I don't use SPEC 0 for all projects. For example, the lazy_loader package doesn't follow SPEC 0. It still supports Python 3.7.

The SPECs are meant to be basic recommendations. Each project will always need to consider when to follow them and when to not follow them. For SPEC 0, some of the endorsing core projects don't intend to follow SPEC 0 exactly.

**Comment by jarrodmillman** [comment]
I am actually happily surprised that the SPECs are being given so much force. I was not sure folks would even pay attention. So I guess it is good that they are being taken so literally and being given so much authority that projects are running into issues.

While we are trying to figure out how to relax the language, it would be helpful if anyone could point to an issue or a PR where these issues are being raised.

**Comment by jarrodmillman** [comment]
Closing since I think we have resolved this with #282 and #283. Feel free to reopen or open another issues, if I am mistaken. Thanks!!
