### ISSUE TITLE
Should SPEC 7 address use of the standard library's `random.random`?

### ISSUE THREAD

**Issue by dschult** [scientific-python/specs#353]
The title of SPEC 7 addresses random number generation generally, but no mention is made of using the Python standard library `random`. I suspect that is because `random` does not work with arrays and folks here work with arrays. So `random` is not used very often. 

I don't know how SPEC 7 should address use of `random`. And it is quite possible that it shouldn't address `random` at all. It seems more oriented towards "don't use RandomState unless you need to" and how to set the seed of `rng` and that we all use the name `rng` to avoid newbies getting hooked on RandomState.  So, `random` doesn't really seem to play into that. But perhaps we should state that we aren't addressing how to use `random`. Perhaps the term "random arrays" applied liberally would make that more clear.

If we do want to address the use of `random` we should mention a nice bit of code that @rkern suggested for NetworkX that takes advantage of allowed subclassing of `random.Random`. The subclass uses the numpy's bit generator as the source of randomness for the functions/routines of the `random` library. NetworkX uses this functionality to allow dev-users to submit code that uses `random` while still allowing advanced users the ability to make all random calls come from a single bit-generator.

I can try to put together a PR, but which approach should I take? Focus the SPEC on random bits from NumPy tools? Or broaden the SPEC to encompass random number generators in Python's `random` library?

**Comment by rkern** [comment]
I would say that SPEC 7 is somewhat narrowly focused on coordinating the transition from current users of `RandomState` (particularly those that followed scikit-learn's `check_random_state()` idiom) to using the modern `Generator`. It's not really intended to be an all-encompassing recommendation on pseudorandomness. I think it would be a distracting digression to address `random`. I don't particularly think the wording in the SPEC needs to change, [it's `Scope` section is pretty clear on the point](https://github.com/scientific-python/specs/blob/main/spec-0007/index.md#scope).

**Comment by dschult** [comment]
Yes -- I agree. The Scope section addresses this concern.
Thanks!
