### ISSUE TITLE
Python 3.8 needed for .tools/tools.py

### ISSUE THREAD

**Issue by ivanov** [scientific-python/specs#93]
There's a walrus operator on line 39 of `.tools/tools.py`, which means Python 3.8 is needed but the `runtime.txt` says 3.7, so I'm not sure which one to fix. 

Not a big deal, but just wanted to flag it.

**Comment by jarrodmillman** [comment]
@stefanv It looks like Netlify v4 supports Python 3.8 with Ubuntu 20.04:
https://github.com/netlify/build-image/blob/focal/CHANGELOG.md

**Comment by stefanv** [comment]
The `runtime.txt` file is only used by Netlify, and Netlify doesn't use `tools.py`; but no harm in updating it anyway.

**Comment by stefanv** [comment]
I guess v4 isn't yet available.
